---
AWSTemplateFormatVersion: '2010-09-09'
Description: '.....'
Parameters:
  Ec2VolumeAutoEnableIO:
    Type: String
    Default: 'false'
    AllowedValues:
    - 'false'
    - 'true'
  Ec2VolumeTagKey:
    Type: String
    Default: CostCenter
Resources:
  Ec2Volume:
    Type: AWS::EC2::Volume
    Properties:
      AutoEnableIO:
        Ref: Ec2VolumeAutoEnableIO
      Size: '5'
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      Tags:
      - Key:
          Ref: Ec2VolumeTagKey
        Value: Ec2VolumeTagValue
