name: 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.5
    - name: Lint Code Base
      uses: github/super-linter@v3.13.5
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        VALIDATE_MD: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true

