name: trivy scanning
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  scan-missconfig:
    name: missconfiguration
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trivy - misconfiguration artifacts
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
